name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev] || true
          python -m pip install -r requirements.txt || true
          python -m pip install -r requirements-dev.txt || true
      - name: Run tests
        run: |
          pytest -q

